# Databricks Apps entry point configuration
# This file is required for Databricks Apps deployment
command: ["uvicorn", "server.app:app", "--host", "0.0.0.0", "--port", "8000"]

env:
  - name: DATABRICKS_CONFIG_PROFILE
    value: "aws-apps"
  - name: ENVIRONMENT
    value: "production"
