# Databricks Apps entry point configuration
# This file is required for Databricks Apps deployment
# Using simplified direct MCP server for streamable HTTP compatibility
command: ["python", "server/app.py"]

env:
  - name: DATABRICKS_CONFIG_PROFILE
    value: "aws-apps"
  - name: ENVIRONMENT
    value: "production"
