app_name: dab-generator

# DABscribe - Streamlit application for Databricks Asset Bundle generation
command:
  - bash
  - start_app.sh

# Environment configuration
env:
  - name: PORT
    value: "8000"  # Databricks Apps requires port 8000
  - name: CLAUDE_API_KEY
    value_from: dabscribe.dab_generator_claude_key
  - name: MCP_REMOTE_URL
    value: https://databricks-mcp-server-1444828305810485.aws.databricksapps.com
  - name: DATABRICKS_CONFIG_PROFILE
    value: aws-apps